const SpecificGroup = () => {
  return <div>Grupo específico</div>;
};
export default SpecificGroup;

//
// CLICAR EM UM GRUPO ESPECÍFICO => GET/BASEURL/GROUPS/GROUPID => VERIFICAR SE EM USERS_ON_GRUP TEM O USERNAME DO USUÁRIO
// IR PARA PÁGINA SPECIFICGROUP => SE O USUÁRIO JÁ TIVER NA LISTA, RENDERIZA GRUPO INSCRITO, SENÃO RENDERIZA GRUPO PARA SE INSCREVER
//
//
//
//
